apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-webui
  labels:
    app: qbittorrent
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: webui
  selector:
    app: qbittorrent
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-torrenting
  labels:
    app: qbittorrent
spec:
  type: NodePort
  ports:
    - port: 6881
      targetPort: 6881
      protocol: TCP
      name: torrenting-tcp
      nodePort: 30881
    - port: 6881
      targetPort: 6881
      protocol: UDP
      name: torrenting-udp
      nodePort: 30882
  selector:
    app: qbittorrent
