jellyfin:
  enableDLNA: true

deploymentStrategy:
  type: Recreate

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-tls-redirect@kubernetescrd
  hosts:
    - host: jellyfin.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: jellyfin-tls
      hosts:
        - jellyfin.local

volumes:
  - name: videos
    hostPath:
      path: /home/nasus/Videos
      type: Directory

volumeMounts:
  - name: videos
    mountPath: /media/Videos

securityContext:
  capabilities:
    add:
      - "SYS_ADMIN"
    drop:
      - "ALL"
  privileged: false
