apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: "v1.19.1"
      helm:
        valueFiles:
          - $values/apps/cert-manager/values.yaml
    - repoURL: https://github.com/Nasus20202/home-cluster.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/Nasus20202/home-cluster
      targetRevision: main
      path: apps/cert-manager/clusterissuer
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
