apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: "1.17.1"
      helm:
        valueFiles:
          - $values/apps/harbor/values.yaml
    - repoURL: https://github.com/Nasus20202/home-cluster.git
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
