apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-k8s-stack
      targetRevision: "0.59.2"
      helm:
        releaseName: vm
        valueFiles:
          - $values/apps/victoria-metrics/values.yaml
    - repoURL: https://github.com/Nasus20202/home-cluster.git
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: victoria-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
