grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.local
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.local
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-tls-redirect@kubernetescrd

  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Viewer
    users:
      allow_sign_up: false
    server:
      domain: grafana.local
