expose:
  tls:
    certSource: secret
    secret:
      secretName: harbor-tls
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-tls-redirect@kubernetescrd
    hosts:
      core: harbor.local

externalURL: https://harbor.local

persistence:
  persistentVolumeClaim:
    registry:
      size: 25Gi
