expose:
  ingress:
    hosts:
      core: harbor.local
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-tls-redirect@kubernetescrd

externalURL: https://harbor.local

persistence:
  persistentVolumeClaim:
    registry:
      size: 25Gi
