global:
  domain: argocd.local

configs:
  params:
    server.insecure: true

  cm:
    timeout.reconciliation: 600s
    users.anonymous.enabled: true

  rbac:
    policy.default: role:user
    policy.csv: |
      p, role:user, applications, get, *, allow
      p, role:user, applications, list, *, allow
      p, role:user, applications, sync, *, allow
      p, role:user, applications, refresh, *, allow
      p, role:user, clusters, get, *, allow
      p, role:user, repositories, get, *, allow
      g, admin, role:admin

server:
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-tls-redirect@kubernetescrd
      cert-manager.io/cluster-issuer: "selfsigned"
    hosts:
      - argocd.local
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.local
dex:
  enabled: false

notifications:
  enabled: false
